<?php

namespace Granola\Components\Menu\MenuItem;

function filter_args(array $args): ?array
{
    // ---------------------------------------
    // Default arguments.
    // ---------------------------------------
    $args = array_merge([
        'classes' => [],
        'item' => null,
        'depth' => 0,
        'max_depth' => null,
        'display_submenu' => false,
        'parent_list_id' => null,
    ], $args);

    // ---------------------------------------
    // Bail early - return null for no output.
    // ---------------------------------------
    if (empty($args['item'])) {
        return null;
    }

    $item = $args['item'];

    if (!is_object($item)) {
        return null;
    }

    // ---------------------------------------
    // Required classes.
    // ---------------------------------------
    $args['classes'] = array_merge([
        'menu-item',
    ], $args['classes'], $item->classes);

    $item_id = 'menu-item-' . $item->ID;

    if (!empty($args['parent_list_id'])) {
        $item_id = $args['parent_list_id'] . '-' . $item_id;
    }

    $args['attributes']['id'] = $item_id;

    $args['link'] = [
        'url' => $item->url,
        'content' => $item->title,
        'target' => $item->target ?: null,
        'attributes' => [
            'title' => $item->attr_title ?: null,
        ],
    ];

    if ($item->url === '#') {
        $args['link']['attributes']['role'] = 'button';
    }

    if (!empty($item->xfn)) {
        $args['link']['attributes']['rel'][] = $item->xfn;
    }

    if (!empty($item->children) && (empty($args['max_depth']) || $args['depth'] + 1 < $args['max_depth'])) {
        $args['display_submenu'] = true;

        // Check if mega menu is enabled (only for depth 0 items)
        $mega_menu_enabled = $args['depth'] === 0 && \get_field('mega_menu_enabled', $item);
        $args['is_mega_menu'] = $mega_menu_enabled;
        $args['classes'][] = $mega_menu_enabled ? 'menu-item--mega-menu' : '';

        // Check if we have global CTA in mega menu dropdown
        $args['mega_menu_cta'] = $mega_menu_enabled ? \get_field('mega_menu_cta', $item) : false;

        $sub_menu_classes = [
            'sub-menu',
            'sub-menu--depth-' . $args['depth'],
            'js-expandable-element',
        ];

        if ($mega_menu_enabled) {
            $sub_menu_classes[] = 'sub-menu--mega';

            // Check if widget column is enabled
            $args['mega_menu_widget_enabled'] = \get_field('mega_menu_widget_enabled', $item);

            if ($args['mega_menu_widget_enabled']) {
                $args['mega_menu_widget'] = [
                    'image' => \get_field('mega_menu_widget_image', $item),
                    'cta' => \get_field('mega_menu_widget_cta', $item),
                ];
            }
        }

        $sub_menu_id = (!empty($args['parent_list_id']) ? $args['parent_list_id'] . '-' : '') . 'sub-menu-' . $item->ID;

        $args['sub-menu-attributes'] = [
            'id' => $sub_menu_id,
            'class' => \Granola\Helpers::build_classes($sub_menu_classes),

            // Initially hide sub-menus.
            'hidden' => true,
            'aria-hidden' => 'true',
        ];

        $args['button'] = [
            'content' => \__('Expand or collapse a sub menu', 'granola'),
            'visually_hidden_text' => true,
            'classes' => ['sub-menu-toggler'],
            'attributes' => [
                'aria-expanded' => 'false',
                'aria-controls' => $sub_menu_id,
                'id' => $sub_menu_id . '-toggler',
            ],
        ];
    }

    // Get menu item image (for depth 1 items in mega menu)
    if ($args['depth'] === 1) {
        $item_image_id = \get_field('mega_menu_item_image', $item);
        if ($item_image_id) {
            $args['item_image'] = $item_image_id;
        }
    }

    // Add multiple
    $args['classes'] = build_menu_item_classes($args['classes'], $item, $args);

    // -------------------------------------------------------------------------
    // Return the filtered args.
    // -------------------------------------------------------------------------
    return $args;
}

/**
 * Generate an array of menu item classes based on the item and its component's arguments.
 *
 * Includes classes similar to the ones generated by `wp_nav_menu()`, though many are commented out
 * as they're generally unnecessary. Uncomment them to use on a project when needed.
 *
 * @link https://developer.wordpress.org/reference/functions/wp_nav_menu/#menu-item-css-classes
 *
 * @param array $classes The initial array of basic menu item classes.
 * @param object $item The menu item object. Typically a WP_Post, but some plugins use a bespoke and not extended type.
 * @param array $args The component arguments used to render the menu item.
 * @return array The generated array of menu item classes.
 */
function build_menu_item_classes(array $classes, object $item, array $args): array
{
    // ID class.
    // $classes[] = 'menu-item--' . $item->ID;

    // Depth class.
    $classes[] = 'menu-item--depth-' . $args['depth'];

    // Object Type class, e.g. taxonomy, post type, etc
    // Includes exception for 'granola-template' post type.
    // $classes[] = 'menu-item--type--' . ($item->object === 'granola-template' ? 'taxonomy' : $item->type);

    // Object Type Name class. e.g. category, event, etc.
    // $classes[] = 'menu-item--object--' . $item->object;

    // Homepage class.
    // Potentially confusing class: Home vs. Front Page.
    if ($item->type === 'post_type' && (int) \get_option('page_on_front') === (int) $item->object_id) {
        $classes[] = 'menu-item--home';
    }

    // Root class (similar but different to home).
    if (!empty($item->url) && \home_url() === rtrim($item->url, '/')) {
        $classes[] = 'menu-item--root';
    }

    // Current Menu Item class.
    if ($item->is_current_item) {
        $classes[] = 'menu-item--current';
    }

    // Parent Menu Item class.
    if ($item->is_current_parent) {
        $classes[] = 'current-menu-parent';
    }

    // Ancestor Menu Item class.
    if ($item->is_current_ancestor) {
        $classes[] = 'current-menu-ancestor';
    }

    // Ancestor Menu Item class.
    if (!empty($item->is_internal_link)) {
        $classes[] = 'menu-item--custom-internal';
    }

    // TODO: .current-{object}-parent
    // TODO: .current-{type}-parent

    // TODO: .current-{object}-ancestor
    // TODO: .current-{type}-ancestor

    // -------------------------------------------------------------------------
    // Menu Items with children (i.e. a submenu).
    // -------------------------------------------------------------------------
    if (!empty($item->children) && (empty($args['max_depth']) || $args['depth'] + 1 <= $args['max_depth'])) {
        // Has sub-menu with child items.
        $classes[] = 'menu-item--has-children';

        // Child Count class.
        // $classes[] = 'menu-item--has-' . count($item->children) . '-children';
    }

    return $classes;
}
